force-app/main/default/objects/MiningSite__c/MiningSite__c.object-meta.xml
<CustomObject>
    <description>Mining location with known ore and estimated amounts.</description>
    <label>Mining Site</label>
    <nameField>
        <label>Mining Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mining Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MiningSite__c/fields/EstimatedWorth__c.field-meta.xml
<CustomField>
    <fullName>EstimatedWorth__c</fullName>
    <description>An estimate of the yearly value of ore at this site.</description>
    <label>Estimated Site Worth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/MiningSiteTriggerTest.cls
@isTest
public with sharing class MiningSiteTriggerTest {
    public MiningSiteTriggerTest() {

    }

    @TestSetup
    static void makeData(){
        List<MiningSite__c> mock_sites = new List<MiningSite__c>();

        for(Integer i = 0; i < 100; i++){
            MiningSite__c site = new MiningSite__c();

            site.EstimatedWorth__c = Math.abs(Math.random());

            site.Name = 'Site' + i;

            if(Math.mod(i, 2) == 0){
                site.Active__c = true;
            }else {
                site.Active__c = false;
            }

            mock_sites.add(site);
        }

        Insert mock_sites;

        AggregateResult result = [SELECT COUNT(Id) FROM MiningSite__c];

        System.assert((Integer)result.get('expr0') > 0, 'NOTHING WAS INSERTED');
    }

    @isTest
    public static void test_update_clamp(){

        List<MiningSite__c> existing = [SELECT EstimatedWorth__c FROM MiningSite__c];

        for(MiningSite__c site : existing){
            site.EstimatedWorth__c = -1;
        }

        Update existing;

        existing = [SELECT EstimatedWorth__c FROM MiningSite__c];

        Boolean hasNegative = false;
        for(MiningSite__c site : existing){
            if(site.EstimatedWorth__c < 0){
                hasNegative = true;
            }
        }

        if(hasNegative){
            System.assert(false, 'Has negative!!');
        }else{
            System.assert(true);
        }
    }

    @isTest
    public static void test_delete_active(){

        List<MiningSite__c> existing = [SELECT EstimatedWorth__c FROM MiningSite__c];

        try{
            Delete existing;
            System.assert(false, 'Should not be able to delete Active, some of which certainly were.');
        }
        catch(Exception e){
            System.assert(true, 'Caught exception from trying to delete an active site, as expected.');
        }

    }
}