force-app/main/default/objects/MiningSite__c/MiningSite__c.object-meta.xml
<CustomObject>
    <description>Mining location with known ore and estimated amounts.</description>
    <label>Mining Site</label>
    <nameField>
        <label>Mining Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mining Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MiningSite__c/fields/EstimatedWorth__c.field-meta.xml
<CustomField>
    <fullName>EstimatedWorth__c</fullName>
    <description>An estimate of the yearly value of ore at this site.</description>
    <label>Estimated Site Worth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/MiningSite__c.field-meta.xml
<CustomField>
    <fullName>MiningSite__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The mining site which ore was sold from.</description>
    <label>Mining Site</label>
    <referenceTo>MiningSite__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderUpdateMiningSite.cls
public with sharing class OrderUpdateMiningSite {

    public static void ChangedActive(List<Order> listOld, List<Order> listNew){
        List<Order> changedActive = new List<Order>();

        for(Integer i = 0; i < listOld.size(); i++){
            if (listOld[i].Status == 'Draft' && listNew[i].Status == 'Activated'){
                changedActive.add(listNew[i]);
            }
        }
        updateFromActivated(changedActive);
    }

    private static void updateFromActivated(List<Order> activated){

        Map<Id, MiningSite__c> sites = new Map<Id, MiningSite__c>([SELECT Id, EstimatedWorth__c FROM MiningSite__c]); // Map has a constructor to automatically do this, as long as implicit conversion takes the list calls that constructor
                                                                                                                    // ok perhaps the implicit conv. didn't work, but it still should be constructed this way.
        List<MiningSite__c> sitesToUpdate = new List<MiningSite__c>();
        
        for(Order ord : activated){

            System.assert(sites.get(ord.MiningSite__c).EstimatedWorth__c > 0, 'Site has only 0 initial value!');

            sites.get(ord.MiningSite__c).EstimatedWorth__c -= ord.TotalAmount; // I take it that ord.MiningSite__c is the ID of the mining site

            System.assert(ord.TotalAmount > 0, 'Order total amount better be greater than 0 as configured for test');

            sitesToUpdate.add(sites.get(ord.MiningSite__c));
        }

        Update sitesToUpdate;
    }
}