force-app/main/default/objects/MiningSite__c/MiningSite__c.object-meta.xml
<CustomObject>
    <description>Mining location with known ore and estimated amounts.</description>
    <label>Mining Site</label>
    <nameField>
        <label>Mining Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mining Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MiningSite__c/fields/Cost_to_Travel__c.field-meta.xml
<CustomField>
    <fullName>Cost_to_Travel__c</fullName>
    <description>This should be an estimate of how much it costs a standard mining ship to travel to this location from the home base of the org, for a feel of the value of making a trip here also considering its approximate yield left worth of ore.</description>
    <label>Cost to Travel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MiningSite__c/fields/EstimatedWorth__c.field-meta.xml
<CustomField>
    <fullName>EstimatedWorth__c</fullName>
    <description>An estimate of the yearly value of ore at this site.</description>
    <label>Estimated Site Worth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MiningSite__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The location of the mining site.</description>
    <label>Location</label>
    <scale>1</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/MiningSite__c/fields/Ore__c.field-meta.xml
<CustomField>
    <fullName>Ore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ore that this site has</description>
    <label>Primary Ore</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Ore</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Mining Sites</relationshipLabel>
    <relationshipName>MiningSites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/MiningSite__c.field-meta.xml
<CustomField>
    <fullName>MiningSite__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The mining site which ore was sold from.</description>
    <label>Mining Site</label>
    <referenceTo>MiningSite__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HomePageExtension.cls
public without sharing class HomePageExtension {
  
    private List<MiningSite__c> top3;
    
    public HomePageExtension(HomePageCustom controller) {
		init();
    }

    public HomePageExtension(ApexPages.StandardController controller) {
		init();
    }
    
    private void init(){
        top3 = [SELECT Active__c, Cost_to_Travel__c, EstimatedWorth__c, Location__c, Name, Ore__r.Name FROM MiningSite__c ORDER BY EstimatedWorth__c DESC LIMIT 3];
    }
    
    private String imageUrlBase(Integer idx){
        
        String base = 'https://image.maps.ls.hereapi.com/mia/1.6/mapview?';
        String zoomAndKey = '&z=11&apiKey=NeXaL6Ng_elBhreu8qmyiHjR6SfHo1haBFZev6507Rc';
        
        Location loc = top3[idx].Location__c;
        
        String lat = String.valueOf(loc.latitude);
        String lon = String.valueOf(loc.longitude);
        
		String url = base + 'c=' + lat + '%2C' + lon + zoomAndKey;

        return url;
    }
    
    public String getImgUrl(){
        return imageUrlBase(0);
    }
    public String getImgUrl2(){
        return imageUrlBase(1);
    }
    public String getImgUrl3(){
        return imageUrlBase(2);
    }
    
    private String toolTipBase(Integer idx){
        return top3[idx].Name + ', primary ore ' + top3[idx].Ore__r.Name;
    }
    
    public String getTooltip(){
        return toolTipBase(0);
    }
    public String getTooltip2(){
        return toolTipBase(1);
    }
    public String getTooltip3(){
        return toolTipBase(2);
    }
}