force-app/main/default/objects/MiningSite__c/MiningSite__c.object-meta.xml
<CustomObject>
    <description>Mining location with known ore and estimated amounts.</description>
    <label>Mining Site</label>
    <nameField>
        <label>Mining Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mining Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MiningSite__c/fields/EstimatedWorth__c.field-meta.xml
<CustomField>
    <fullName>EstimatedWorth__c</fullName>
    <description>An estimate of the yearly value of ore at this site.</description>
    <label>Estimated Site Worth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MiningSite__c/fields/Ore__c.field-meta.xml
<CustomField>
    <fullName>Ore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ore that this site has</description>
    <label>Primary Ore</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Ore</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Mining Sites</relationshipLabel>
    <relationshipName>MiningSites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HomePageTest.cls
@isTest
public class HomePageTest {
    
    @TestSetup
    public static void makeData(){
        
        Product2 ore = new Product2();
        
        ore.Family = 'Ore';
        ore.Name = 'TestOre';
        
        Insert ore;
        
        ore = [SELECT id FROM Product2 WHERE Family = 'Ore'];
        
        List<MiningSite__c> lms = new List<MiningSite__c>();
        
        for(integer i = 0; i < 10; i++){
            MiningSite__c site = new MiningSite__c();
            site.EstimatedWorth__c = Math.random() * 200000;
            site.Ore__c = ore.Id;
            site.Name = String.valueOf(i);
            site.Location__Latitude__s = i+1;
            site.Location__Longitude__s = i+2;
            lms.add(site);
        }
        
        Insert lms;
    }
    
    
    @isTest
    public static void TP_tooltips(){
        HomePageCustom controller = new HomePageCustom();
        HomePageExtension extension = new HomePageExtension(controller);
        
        System.assert(extension.getToolTip().contains('TestOre'));
        System.assert(extension.getToolTip2().contains('TestOre'));
        System.assert(extension.getToolTip3().contains('TestOre'));
    }
    
    @isTest
    public static void TP_imgUrl(){
        HomePageCustom controller = new HomePageCustom();
        HomePageExtension extension = new HomePageExtension(controller);
        
        System.assert(extension.getImgUrl().contains('&z=11&apiKey=NeXaL6Ng_elBhreu8qmyiHjR6SfHo1haBFZev6507Rc'));
        System.assert(extension.getImgUrl().contains('https://image.maps.ls.hereapi.com/mia/1.6/mapview?'));
        
        System.assert(extension.getImgUrl2().contains('&z=11&apiKey=NeXaL6Ng_elBhreu8qmyiHjR6SfHo1haBFZev6507Rc'));
        System.assert(extension.getImgUrl2().contains('https://image.maps.ls.hereapi.com/mia/1.6/mapview?'));
        
        System.assert(extension.getImgUrl3().contains('&z=11&apiKey=NeXaL6Ng_elBhreu8qmyiHjR6SfHo1haBFZev6507Rc'));
        System.assert(extension.getImgUrl3().contains('https://image.maps.ls.hereapi.com/mia/1.6/mapview?'));
    }
    
    @isTest
    public static void TP_homepagecustom(){
        HomePageCustom controller = new HomePageCustom();
        System.assert(! controller.getbRender());
        
        System.assert(controller.getLead().getSObjectType().GetDescribe() == Schema.SObjectType.Lead);
        
        controller.save();
        
        System.assert(controller.getbRender());
        
    }
}